
%token TOKEN_EOF

%token TOKEN_NS_SEPARATOR
%token TOKEN_WHITESPACE
%token TOKEN_ERROR
%token TOKEN_ANGLE_LEFT
%token TOKEN_ANGLE_RIGHT
%token TOKEN_FORWARD_SLASH
%token TOKEN_CURLY_START
%token TOKEN_CURLY_END
%token TOKEN_ELLIPSIS
%token TOKEN_EQUALS
%token TOKEN_TAG_NAME
%token TOKEN_XHP_TEXT
%token TOKEN_XHP_ENTITY
